### ISSUE TITLE
Install GIT but not identifying the version 

### ISSUE THREAD

**Issue by isoftjhang** [ashraf789/Android-POS#2]
1 Errors one GIT version error 

Now this problem I attach the image 

![image](https://user-images.githubusercontent.com/5946648/64277835-bdd45800-cf64-11e9-8f59-09df4fc9ded5.png)
 
I also need to remove the ad code ..  

Thanks

**Comment by isoftjhang** [comment]
I compiled and it run now ,  Your code well, I am working on it to make it more reliable ..

Thanks

**Comment by ashraf789** [comment]
Great to know you like to contribute. If you think this issue is solved then you can close it.
Thanks
